const vehicles=[
{id:1,name:'Renault Clio 6 Esprit Alpine',prices:{'24H semaine':105,'24H week-end':130,'48H week-end':260,'72H week-end':400,'4 jours':450,'Semaine complète':520},caution:1500,image:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',type:'Citadine premium'},
{id:2,name:'Renault Clio 5 Alpine',prices:{'24H semaine':95,'24H week-end':120,'48H week-end':240,'72H week-end':380,'4 jours':430,'Semaine complète':480},caution:1500,image:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',type:'Citadine sport'},
{id:3,name:'Volkswagen Golf 8.5 R blanche',prices:{'24H semaine':270,'24H week-end':410,'48H week-end':740,'72H week-end':920,'4 jours':1050,'Semaine complète':1390},caution:3000,image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',type:'Berline sportive'},
{id:4,name:'Volkswagen Golf 8.5 R noire',prices:{'24H semaine':280,'24H week-end':420,'48H week-end':760,'72H week-end':950,'4 jours':1080,'Semaine complète':1420},caution:3000,image:'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=80',type:'Berline sportive'},
{id:5,name:'Audi RS3 Sportback',prices:{'24H semaine':360,'24H week-end':420,'48H week-end':620,'72H week-end':1050,'4 jours':1100,'Semaine complète':1750},caution:5000,image:'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',type:'Sportive'},
{id:6,name:'Audi RS3 noire',prices:{'24H semaine':370,'24H week-end':440,'48H week-end':650,'72H week-end':1080,'4 jours':1150,'Semaine complète':1800},caution:5000,image:'https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=900&q=80',type:'Sportive premium'},
{id:7,name:'Mercedes A45 S AMG jaune',prices:{'24H semaine':390,'24H week-end':450,'48H week-end':700,'72H week-end':1100,'4 jours':1200,'Semaine complète':1850},caution:4000,image:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=80',type:'Performance'},
{id:8,name:'Mercedes A45 S AMG grise',prices:{'24H semaine':400,'24H week-end':470,'48H week-end':730,'72H week-end':1130,'4 jours':1230,'Semaine complète':1900},caution:4000,image:'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',type:'Performance'},
{id:9,name:'Audi RS6',prices:{'24H semaine':450,'24H week-end':550,'48H week-end':880,'72H week-end':1200,'4 jours':1650,'Semaine complète':2050},caution:10000,image:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80',type:'Grand tourer'}];
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);const get=(id)=>vehicles.find(v=>v.id==id);const days=(a,b)=>Math.ceil((new Date(b)-new Date(a))/86400000);const weekend=d=>[0,6].includes(new Date(d).getDay());
function quote(v,a,b){let n=days(a,b);if(!n||n<1)return{total:0,label:'Dates à compléter'};if(n>=7)return{total:v.prices['Semaine complète'],label:'Semaine complète'};if(n==4)return{total:v.prices['4 jours'],label:'4 jours'};if(n==3)return{total:v.prices['72H week-end'],label:'72H week-end'};if(n==2)return{total:v.prices['48H week-end'],label:'48H week-end'};return{total:v.prices[weekend(a)?'24H week-end':'24H semaine'],label:weekend(a)?'24H week-end':'24H semaine'}}
function overlaps(v,a,b){return JSON.parse(localStorage.lkReservations||'[]').some(r=>r.vehicleId==v.id&&r.status!=='cancelled'&&new Date(a)<new Date(r.end)&&new Date(b)>new Date(r.start))}
function renderCars(){let el=document.querySelector('#catalogue-grid');if(!el)return;el.innerHTML=vehicles.map(v=>`<article class="car"><div class="car-img" style="background-image:url('${v.image}')"></div><div class="car-body"><h3>${v.name}</h3><span class="type">${v.type}</span><div class="price-list">${Object.entries(v.prices).map(([k,n])=>`<div><span>${k}</span><b>${euro(n)}</b></div>`).join('')}</div><span class="caution">Caution : ${euro(v.caution)}</span></div></article>`).join('')}
function fillSelect(){let s=document.querySelector('#vehicle');if(!s)return;s.innerHTML=vehicles.map(v=>`<option value="${v.id}">${v.name}</option>`).join('');['vehicle','start','end'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',update));update()}
function update(){let v=get(document.querySelector('#vehicle')?.value||1),a=document.querySelector('#start')?.value,b=document.querySelector('#end')?.value,s=document.querySelector('#summary');if(!s)return;let q=quote(v,a,b);s.innerHTML=`<span>${v.name} · ${q.label}</span><span>Location : <strong>${euro(q.total)}</strong></span><span>Caution : <strong>${euro(v.caution)}</strong></span>`}
function booking(){let f=document.querySelector('#booking-form');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();let v=get(document.querySelector('#vehicle').value),a=document.querySelector('#start').value,b=document.querySelector('#end').value;if(!a||!b||new Date(b)<=new Date(a))return alert('Sélectionnez des dates valides.');if(overlaps(v,a,b))return alert('Ce véhicule est déjà réservé sur cette période. Choisissez d’autres dates.');let q=quote(v,a,b),r={id:Date.now(),vehicleId:v.id,vehicle:v.name,start:a,end:b,name:document.querySelector('#customer').value,phone:document.querySelector('#phone').value,email:document.querySelector('#email').value,location:document.querySelector('#location').value,total:q.total,caution:v.caution,status:'pending'};let all=JSON.parse(localStorage.lkReservations||'[]');all.push(r);localStorage.lkReservations=JSON.stringify(all);document.querySelector('#booking-message').textContent='Demande enregistrée. LK RENT vous recontactera pour confirmation.';f.reset();update()})}
renderCars();fillSelect();booking();
